Yandex test added, some improvements to the base project structure
dubograev/qa.guru_homework_lesson7 pull request #1
Opened 2020-12-02 18:57 UTC by Domadin

2020-12-02 18:59 UTC, Domadin commented
Добавлен гитигнор как один из самых важных файлов в любом проекте
Добавлен gradle wrapper и все сопутствующие файлы, ибо по документации gradle он должен быть в проекте
Пофикшена нехватка пакета в базовом гугловском тесте
Добавлен тест на яндекс

2020-12-04 11:40 UTC, dubograev approved these changes

2020-12-04 11:41 UTC, dubograev reviewed
Just a comment

2020-12-04 11:44 UTC, dubograev requested changes
Please add a space between class declaration and test annotation

2020-12-06 19:21 UTC, merged